frontend_home:
    pattern:  /home
    defaults: { _controller: FrontendBundle:Article:all }
    
show_article:
    pattern:  /articulo/{id}
    defaults: { _controller: FrontendBundle:Article:show }
    
show_article:
    pattern:  /art
    defaults: { _controller: FrontendBundle:Article:index }
