frontend_homepage:
    pattern:  /hello
    defaults: { _controller: FrontendBundle:Default:index }


#frontendBundle_article:
#    resource: "@FrontendBundle/Resources/config/routing/article.yml"
#    prefix:   /articulo
#    
#frontendBundle_problem:
#    resource: "@FrontendBundle/Resources/config/routing/problem.yml"
#    prefix:   /problem
#    
#frontendBundle_competition:
#    resource: "@FrontendBundle/Resources/config/routing/competition.yml"
#    prefix:   /competition