newsBundle_article:
    resource: "@NewsBundle/Resources/config/routing/article.yml"
    prefix:   /articulo
  
newsBundle_comment:
    resource: "@NewsBundle/Resources/config/routing/comment.yml"
    prefix:   /comentario
