newsBundle_article:
    resource: "@NewsBundle/Resources/config/routing/article.yml"
    prefix:   /article
  
newsBundle_comment:
    resource: "@NewsBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
