comment:
    pattern:  /
    defaults: { _controller: "NewsBundle:Comment:index" }

comment_list:
    pattern: /listar/
    defaults: { _controller: "NewsBundle:Comment:list" }
    options:
        expose: true

comment_edit:
    pattern:  /{id}/editar/
    defaults: { _controller: "NewsBundle:Comment:edit" }

comment_update:
    pattern:  /{id}/actualizar/
    defaults: { _controller: "NewsBundle:Comment:update" }
    requirements: { _method: post|put }

comment_delete:
    pattern:  /{id}/eliminar/
    defaults: { _controller: "NewsBundle:Comment:delete" }
    
comment_publish:
    pattern:  /{id}/publish/
    defaults: { _controller: "NewsBundle:Comment:publish" } 
    requirements: { _method: post }
    options:
        expose: true
    
