competition_index:
    pattern:  /competition/
    defaults: { _controller: CompetitionBundle:Competition:index }
    
competition_create:
    pattern:  /competition/create
    defaults: { _controller: CompetitionBundle:Competition:create }
 
competition_list:
    pattern:  /competition/list
    defaults: { _controller: CompetitionBundle:Competition:list }
    
competition_update:
    pattern:  /competition/update/{id}
    defaults: { _controller: CompetitionBundle:Competition:edit }

competition_delete:
    pattern:  /competition/delete/{id}
    defaults: { _controller: CompetitionBundle:Competition:delete }