competitionBundle_competition:
    resource: "@CompetitionBundle/Resources/config/routing/competition.yml"
    prefix:   /competencia
    
competitionBundle_team:
    resource: "@CompetitionBundle/Resources/config/routing/team.yml"
    prefix:   /equipo