problemBundle_problem:
    resource: "@ProblemBundle/Resources/config/routing/problem.yml"
    prefix:   /problem

problemBundle_sending:
    resource: "@ProblemBundle/Resources/config/routing/sending.yml"
    prefix:   /sending