parameters:
#    problem.example.class: DBOJ\ProblemBundle\Example

services:
    dboj.sending:
        class: DBOJ\ProblemBundle\Services\Sending
        arguments: [@doctrine]
        
    dboj.problem:
        class: DBOJ\ProblemBundle\Services\Problem
        arguments: [@doctrine]
