parameters:
#    problem.example.class: DBOJ\ProblemBundle\Example

services:
#    problem.example:
#        class: %problem.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
