commonBundle_nomenclator:
    resource: "@CommonBundle/Resources/config/routing/nomenclator.yml"
    prefix:   /nomenclador

commonBundle_catalog:
    resource: "@CommonBundle/Resources/config/routing/catalog.yml"
    prefix:   /catalogo