userBundle_user_backend:
    resource: "@UserBundle/Resources/config/routing/backend/user.yml"
    prefix:   /admin/usuario
    
#userBundle_user_frontend:
#    resource: "@UserBundle/Resources/config/routing/user.yml"
#    prefix:   /admin/usuario